/* eslint-disable key-spacing */
export default {
    NGHTTP2: {
        ERR: { FRAME: { SIZE: { ERROR: -522 }}},
        SESSION: { SERVER: 0, CLIENT: 1 },

        STREAM: {
            CLOSED: 5,
            STATE: {
                IDLE: 1,
                OPEN: 2,
                RESERVED: { LOCAL: 3, REMOTE: 4 },
                HALF: { CLOSED: { LOCAL: 5, REMOTE: 6 }},
                CLOSED: 7,
            },

        },

        FLAG: {
            NONE: 0,
            ACK: 1,
            PADDED: 8,
            PRIORITY: 32,
            END: { STREAM: 1, HEADERS: 4 },
        },

        SETTINGS: {
            TIMEOUT: 4,
            HEADER : { TABLE: { SIZE: 1 }},
            INITIAL: { WINDOW: { SIZE: 4 }},
            ENABLE : { PUSH: 2, CONNECT: { PROTOCOL: 8 }},
            MAX    : {
                CONCURRENT: { STREAMS: 3 },
                FRAME: { SIZE: 5 },
                HEADER: { LIST: { SIZE: 6 }},
            },
        },

        NO          : { ERROR: 0 },
        PROTOCOL    : { ERROR: 1 },
        INTERNAL    : { ERROR: 2 },
        FLOW        : { CONTROL: { ERROR: 3 }},
        FRAME       : { SIZE: { ERROR: 6 }},
        REFUSED     : { STREAM: 7 },
        CANCEL      : 8,
        COMPRESSION : { ERROR: 9 },
        CONNECT     : { ERROR: 10 },
        ENHANCE     : { YOUR: { CALM: 11 }},
        INADEQUATE  : { SECURITY: 12 },
        HTTP        : { 1: { 1: { REQUIRED: 13 }}},
        DEFAULT     : { WEIGHT: 16 },
    },

    DEFAULT: {
        SETTINGS: {
            HEADER : { TABLE: { SIZE: 4096 }},
            ENABLE : { PUSH: 1, CONNECT: { PROTOCOL: 0 }},
            INITIAL: { WINDOW: { SIZE: 65535 }},
            MAX    : {
                CONCURRENT : { STREAMS: 4294967295 },
                FRAME      : { SIZE: 16384 },
                HEADER     : { LIST: { SIZE: 65535 }},
            },
        },
    },

    MAX: {
        MAX     : { FRAME : { SIZE: 16777215 }},
        INITIAL : { WINDOW: { SIZE: 2147483647 }},
    },
    MIN    : { MAX: { FRAME: { SIZE: 16384 }}},
    PADDING: { STRATEGY: { MAX: 2, NONE: 0, ALIGNED: 1, CALLBACK: 1 }},

    HTTP2: {
        HEADER: {
            STATUS    : ':status',
            METHOD    : ':method',
            AUTHORITY : ':authority',
            SCHEME    : ':scheme',
            PATH      : ':path',
            PROTOCOL  : ':protocol',

            ACCEPT    : {
                ENCODING : 'accept-encoding',
                LANGUAGE : 'accept-language',
                RANGES   : 'accept-ranges',
                ACCEPT   : 'accept',
                CHARSET  : 'accept-charset',
            },

            ACCESS: {
                CONTROL: {
                    EXPOSE : { HEADERS : 'access-control-expose-headers' },
                    MAX    : { AGE     : 'access-control-max-age' },
                    REQUEST: {
                        HEADERS : 'access-control-request-headers',
                        METHOD  : 'access-control-request-method',
                    },
                    ALLOW : {
                        CREDENTIALS : 'access-control-allow-credentials',
                        HEADERS     : 'access-control-allow-headers',
                        METHODS     : 'access-control-allow-methods',
                        ORIGIN      : 'access-control-allow-origin',
                    },

                },
            },

            CONTENT       : {
                MD5         : 'content-md5',
                TYPE        : 'content-type',
                RANGE       : 'content-range',
                LENGTH      : 'content-length',
                ENCODING    : 'content-encoding',
                LANGUAGE    : 'content-language',
                LOCATION    : 'content-location',
                DISPOSITION : 'content-disposition',
                SECURITY    : { POLICY: 'content-security-policy' },
            },

            IF: {
                RANGE      : 'if-range',
                MATCH      : 'if-match',
                NONE       : { MATCH: 'if-none-match' },
                MODIFIED   : { SINCE: 'if-modified-since' },
                UNMODIFIED : { SINCE: 'if-unmodified-since' },
            },

            UPGRADE: {
                UPGRADE: 'upgrade',
                INSECURE: { REQUESTS: 'upgrade-insecure-requests' },
            },

            X: {
                CONTENT  : { TYPE       : { OPTIONS: 'x-content-type-options' }},
                FRAME    : { OPTIONS    : 'x-frame-options' },
                XSS      : { PROTECTION : 'x-xss-protection' },
                FORWARDED: { FOR        : 'x-forwarded-for' },
            },

            PROXY: {
                CONNECTION: 'proxy-connection',
                AUTHENTICATE: 'proxy-authenticate',
                AUTHORIZATION: 'proxy-authorization',
            },

            USER     : { AGENT       : 'user-agent' },
            KEEP     : { ALIVE       : 'keep-alive' },
            SET      : { COOKIE      : 'set-cookie' },
            LAST     : { MODIFIED    : 'last-modified' },
            ALT      : { SVC         : 'alt-svc' },
            EARLY    : { DATA        : 'early-data' },
            MAX      : { FORWARDS    : 'max-forwards' },
            RETRY    : { AFTER       : 'retry-after' },
            WWW      : { AUTHENTICATE: 'www-authenticate' },
            TRANSFER : { ENCODING    : 'transfer-encoding' },
            HTTP2    : { SETTINGS    : 'http2-settings' },
            CACHE    : { CONTROL     : 'cache-control' },
            EXPECT   : { CT          : 'expect-ct', EXPECT: 'expect' },
            TIMING   : { ALLOW       : { ORIGIN  : 'timing-allow-origin' }},
            STRICT   : { TRANSPORT   : { SECURITY: 'strict-transport-security' }},

            AGE           : 'age',
            AUTHORIZATION : 'authorization',
            CONNECTION    : 'connection',
            DATE          : 'date',
            ETAG          : 'etag',
            COOKIE        : 'cookie',
            FORWARDED     : 'forwarded',
            HOST          : 'host',
            TE            : 'te',
            LINK          : 'link',
            RANGE         : 'range',
            SERVER        : 'server',
            REFERER       : 'referer',
            LOCATION      : 'location',
            VARY          : 'vary',
            ORIGIN        : 'origin',
            PURPOSE       : 'purpose',
            PRIORITY      : 'priority',
            ALLOW         : 'allow',
            DNT           : 'dnt',
            EXPIRES       : 'expires',
            FROM          : 'from',
            PREFER        : 'prefer',
            REFRESH       : 'refresh',
            TRAILER       : 'trailer',
            TK            : 'tk',
            VIA           : 'via',
            WARNING       : 'warning',

        },
        METHOD: {
            ACL               : 'ACL',
            BIND              : 'BIND',
            CHECKIN           : 'CHECKIN',
            CHECKOUT          : 'CHECKOUT',
            CONNECT           : 'CONNECT',
            COPY              : 'COPY',
            DELETE            : 'DELETE',
            GET               : 'GET',
            HEAD              : 'HEAD',
            LABEL             : 'LABEL',
            LINK              : 'LINK',
            LOCK              : 'LOCK',
            MERGE             : 'MERGE',
            MKACTIVITY        : 'MKACTIVITY',
            MKCALENDAR        : 'MKCALENDAR',
            MKCOL             : 'MKCOL',
            MKREDIRECTREF     : 'MKREDIRECTREF',
            MKWORKSPACE       : 'MKWORKSPACE',
            MOVE              : 'MOVE',
            OPTIONS           : 'OPTIONS',
            ORDERPATCH        : 'ORDERPATCH',
            PATCH             : 'PATCH',
            POST              : 'POST',
            PRI               : 'PRI',
            PROPFIND          : 'PROPFIND',
            PROPPATCH         : 'PROPPATCH',
            PUT               : 'PUT',
            REBIND            : 'REBIND',
            REPORT            : 'REPORT',
            SEARCH            : 'SEARCH',
            TRACE             : 'TRACE',
            UNBIND            : 'UNBIND',
            UNCHECKOUT        : 'UNCHECKOUT',
            UNLINK            : 'UNLINK',
            UNLOCK            : 'UNLOCK',
            UPDATE            : 'UPDATE',
            UPDATEREDIRECTREF : 'UPDATEREDIRECTREF',
            VERSION           : { CONTROL: 'VERSION-CONTROL' },
            BASELINE          : { CONTROL: 'BASELINE-CONTROL' },
        },
    },
    HTTP: {
        STATUS: {
            CONTINUE      : 100,
            PROCESSING    : 102,
            OK            : 200,
            CREATED       : 201,
            ACCEPTED      : 202,
            FOUND         : 302,
            UNAUTHORIZED  : 401,
            FORBIDDEN     : 403,
            CONFLICT      : 409,
            GONE          : 410,
            TEAPOT        : 418,
            LOCKED        : 423,
            NOT           : {
                MODIFIED    : 304,
                FOUND       : 404,
                ACCEPTABLE  : 406,
                IMPLEMENTED : 501,
                EXTENDED    : 510,
            },
            SWITCHING     : { PROTOCOLS      : 101 },
            EARLY         : { HINTS          : 103 },
            NO            : { CONTENT        : 204 },
            RESET         : { CONTENT        : 205 },
            PARTIAL       : { CONTENT        : 206 },
            MULTI         : { STATUS         : 207 },
            ALREADY       : { REPORTED       : 208 },
            IM            : { USED           : 226 },
            MULTIPLE      : { CHOICES        : 300 },
            MOVED         : { PERMANENTLY    : 301 },
            SEE           : { OTHER          : 303 },
            USE           : { PROXY          : 305 },
            TEMPORARY     : { REDIRECT       : 307 },
            PERMANENT     : { REDIRECT       : 308 },
            PAYMENT       : { REQUIRED       : 402 },
            LENGTH        : { REQUIRED       : 411 },
            EXPECTATION   : { FAILED         : 417 },
            MISDIRECTED   : { REQUEST        : 421 },
            UNPROCESSABLE : { ENTITY         : 422 },
            FAILED        : { DEPENDENCY     : 424 },
            UPGRADE       : { REQUIRED       : 426 },
            SERVICE       : { UNAVAILABLE    : 503 },
            GATEWAY       : { TIMEOUT        : 504 },
            INSUFFICIENT  : { STORAGE        : 507 },
            LOOP          : { DETECTED       : 508 },
            BAD           : { REQUEST        : 400, GATEWAY  : 502 },
            PRECONDITION  : { FAILED         : 412, REQUIRED : 428 },
            TOO           : { EARLY          : 425, MANY     : { REQUESTS: 429 }},
            REQUEST       : { TIMEOUT        : 408, HEADER   : { FIELDS: { TOO: { LARGE: 431 }}}},
            NON           : { AUTHORITATIVE  : { INFORMATION : 203 }},
            METHOD        : { NOT            : { ALLOWED     : 405 }},
            PROXY         : { AUTHENTICATION : { REQUIRED    : 407 }},
            PAYLOAD       : { TOO            : { LARGE       : 413 }},
            URI           : { TOO            : { LONG        : 414 }},
            UNSUPPORTED   : { MEDIA          : { TYPE        : 415 }},
            RANGE         : { NOT            : { SATISFIABLE : 416 }},
            INTERNAL      : { SERVER         : { ERROR       : 500 }},
            VARIANT       : { ALSO           : { NEGOTIATES  : 506 }},
            BANDWIDTH     : { LIMIT          : { EXCEEDED    : 509 }},
            NETWORK       : { AUTHENTICATION : { REQUIRED    : 511 }},
            UNAVAILABLE   : { FOR            : { LEGAL       : { REASONS   : 451 }}},
            HTTP          : { VERSION        : { NOT         : { SUPPORTED : 505 }}},
        },
    },
    MIME: {
        'content-type'                      : 'content-type',
        '.ct'                               : 'content-type',
        ct                                  : 'content-type',
        '.type'                             : 'content-type',
        type                                : 'content-type',
        '.ctype'                            : 'content-type',
        ctype                               : 'content-type',
        'content-length'                    : 'content-length',
        '.cl'                               : 'content-length',
        cl                                  : 'content-length',
        '.size'                             : 'content-length',
        size                                : 'content-length',
        '.clength'                          : 'content-length',
        clength                             : 'content-length',
        'multipart/form-data'               : 'multipart/form-data',
        '.form'                             : 'multipart/form-data',
        form                                : 'multipart/form-data',
        '.multipart'                        : 'multipart/form-data',
        multipart                           : 'multipart/form-data',
        'application/x-www-form-urlencoded' : 'application/x-www-form-urlencoded',
        '.query'                            : 'application/x-www-form-urlencoded',
        query                               : 'application/x-www-form-urlencoded',
        '.urlenc'                           : 'application/x-www-form-urlencoded',
        urlenc                              : 'application/x-www-form-urlencoded',
        'application/json'                  : 'application/json',
        '.map'                              : 'application/json',
        map                                 : 'application/json',
        '.json'                             : 'application/json',
        json                                : 'application/json',
        'application/javascript'            : 'application/javascript',
        '.js'                               : 'application/javascript',
        js                                  : 'application/javascript',
        '.mjs'                              : 'application/javascript',
        mjs                                 : 'application/javascript',
        'application/octet-stream'          : 'application/octet-stream',
        '.bin'                              : 'application/octet-stream',
        bin                                 : 'application/octet-stream',
        '.dmg'                              : 'application/octet-stream',
        dmg                                 : 'application/octet-stream',
        '.iso'                              : 'application/octet-stream',
        iso                                 : 'application/octet-stream',
        '.img'                              : 'application/octet-stream',
        img                                 : 'application/octet-stream',
        '.buffer'                           : 'application/octet-stream',
        buffer                              : 'application/octet-stream',
        'application/zip'                   : 'application/zip',
        '.zip'                              : 'application/zip',
        zip                                 : 'application/zip',
        '.tar'                              : 'application/zip',
        tar                                 : 'application/zip',
        'application/font-woff'             : 'application/font-woff',
        '.woff'                             : 'application/font-woff',
        woff                                : 'application/font-woff',
        'application/x-font-bdf'            : 'application/x-font-bdf',
        '.bdf'                              : 'application/x-font-bdf',
        bdf                                 : 'application/x-font-bdf',
        'application/x-font-otf'            : 'application/x-font-otf',
        '.otf'                              : 'application/x-font-otf',
        otf                                 : 'application/x-font-otf',
        'application/x-font-pcf'            : 'application/x-font-pcf',
        '.pcf'                              : 'application/x-font-pcf',
        pcf                                 : 'application/x-font-pcf',
        'application/x-font-snf'            : 'application/x-font-snf',
        '.snf'                              : 'application/x-font-snf',
        snf                                 : 'application/x-font-snf',
        'application/x-font-ttf'            : 'application/x-font-ttf',
        '.ttf'                              : 'application/x-font-ttf',
        ttf                                 : 'application/x-font-ttf',
        '.ttc'                              : 'application/x-font-ttf',
        ttc                                 : 'application/x-font-ttf',
        'image/gif'                         : 'image/gif',
        '.gif'                              : 'image/gif',
        gif                                 : 'image/gif',
        'image/jpeg'                        : 'image/jpeg',
        '.jpg'                              : 'image/jpeg',
        jpg                                 : 'image/jpeg',
        '.jpeg'                             : 'image/jpeg',
        jpeg                                : 'image/jpeg',
        'image/png'                         : 'image/png',
        '.png'                              : 'image/png',
        png                                 : 'image/png',
        'image/svg'                         : 'image/svg',
        '.xml'                              : 'image/svg',
        xml                                 : 'image/svg',
        '.svg'                              : 'image/svg',
        svg                                 : 'image/svg',
        '.svgz'                             : 'image/svg',
        svgz                                : 'image/svg',
        'image/webp'                        : 'image/webp',
        '.webp'                             : 'image/webp',
        webp                                : 'image/webp',
        'image/x-icon'                      : 'image/x-icon',
        '.ico'                              : 'image/x-icon',
        ico                                 : 'image/x-icon',
        'text/css'                          : 'text/css',
        '.css'                              : 'text/css',
        css                                 : 'text/css',
        'text/csv'                          : 'text/csv',
        '.csv'                              : 'text/csv',
        csv                                 : 'text/csv',
        'text/xml'                          : 'text/xml',
        'text/html'                         : 'text/html',
        '.html'                             : 'text/html',
        html                                : 'text/html',
        'text/jsx'                          : 'text/jsx',
        '.jsx'                              : 'text/jsx',
        jsx                                 : 'text/jsx',
        'text/less'                         : 'text/less',
        '.less'                             : 'text/less',
        less                                : 'text/less',
        'text/yaml'                         : 'text/yaml',
        '.yml'                              : 'text/yaml',
        yml                                 : 'text/yaml',
        '.yaml'                             : 'text/yaml',
        yaml                                : 'text/yaml',
        'text/x-markdown'                   : 'text/x-markdown',
        '.md'                               : 'text/x-markdown',
        md                                  : 'text/x-markdown',
        'text/event-stream'                 : 'text/event-stream',
        '.sse'                              : 'text/event-stream',
        sse                                 : 'text/event-stream',
        'text/plain'                        : 'text/plain',
        '.txt'                              : 'text/plain',
        txt                                 : 'text/plain',
    },
}
